### ISSUE TITLE
UX improvement: Updating state on chain prior to or during the challenge period isnt clear

### ISSUE THREAD

**Issue by ArjunBhuptani** [ConnextProject/ethcalate-moneyshot#108]
Right now, it isn't clear that, when a channel enters the challenge period, the option to update state on-chain is only for dispute resolution purposes. Same goes for updating the state on-chain before closing.

In the ideal case, the user cannot tell the difference between a channel-based transaction and a regular one. We obviously cant do this for moneyshot right now (we need to do it eventually), but for now we should make it so that the latest accepted state is automatically "suggested" when closing channel?

**Comment by ArjunBhuptani** [comment]
This is a bigger design decision, let's discuss today EOD. @LayneHaber @rhlsthrm @kevkim11

**Comment by LayneHaber** [comment]
@ArjunBhuptani @rhlsthrm 

Do we have any suggestions here? or do you and i want to do a call @ArjunBhuptani? also, we should make sure it says 'both' next to the transaction you update or countersign since that doesnt seem to be working properly
