### ISSUE TITLE
No tests for failure modes

### ISSUE THREAD

**Issue by jtremback** [ConnextProject/ethcalate-moneyshot#45]
Skimming your tests, it looks like you just test the happy path. Compare this to Guac's tests:

<img width="744" alt="image" src="https://user-images.githubusercontent.com/1335122/38581231-15a9b404-3cc1-11e8-9e28-1e5d1ddc2063.png">

Ethcalate is not testing any of the scenarios where someone is stopped from attacking the contract.

**Comment by ArjunBhuptani** [comment]
Will redo tests with the VC framework
