### ISSUE TITLE
Return id from `openChannel`

### ISSUE THREAD

**Issue by jtremback** [ConnextProject/ethcalate-moneyshot#47]
Otherwise, how is the off chain code going to know what it is?

**Comment by rhlsthrm** [comment]
Right now the off chain code looks the id up through the activeIds mapping.
Also you can't get return values from web3 transactions, so we would have
to rely on the event anyways.

**Comment by jtremback** [comment]
Oh, my bad lol. Been a few months. 

Seems like this makes it so that I have to wait and then check back when making a new channel. I don't see any advantage to that. In guac, the channelId is supplied by the offchain code when making a new channel, and rejected if a channel with that ID already exists. Why not just do that? Then making a channel involves one call and can be done in one step.

**Comment by ArjunBhuptani** [comment]
Hey @jtremback we're talking about this now. What is the benefit to generating ID offchain? Making a channel still involves only one call at the moment (two if you include joinChannel for the counterparty, is that what you mean?)
