### ISSUE TITLE
UX around state update/challenge

### ISSUE THREAD

**Issue by rhlsthrm** [ConnextProject/ethcalate-moneyshot#63]
Start challenge button should use the new paradigm. Right now it will submit two transactions in a row, one for state update and one for starting challenge. This will still fail on the UI side if there is no countersigned transaction. We need to do a couple things here:

[] Allow challenge without state update
[] Prompt user when challenging if they want to use the latest on chain state or update state with a countersigned tx
[] Allow user to submit a valid state update from the tx list

**Comment by ArjunBhuptani** [comment]
Still a little weird on the transaction sender side:

If A opens with B, sends a few transactions and then goes to close, A still has to wait for B to respond and countersign. B can hold A's deposit hostage and force A to send more money before B signs the updates.

This is probably fine for v0 but we should think about ways to improve for v1.
