### ISSUE TITLE
Port Moneyshot over to Redux and make it work with drizzle

### ISSUE THREAD

**Issue by ArjunBhuptani** [ConnextProject/ethcalate-moneyshot#88]
- [x] port to Web3 1.0
- [x] drizzle integration (wtf goes into this? @LayneHaber @rhlsthrm )
- [x] redux port

**Comment by LayneHaber** [comment]
Put into redux store:
- [ ] myChannels (all)
- [ ] fetching (App, DesktopComponent, ChannelMenu
- [ ] channelType (ChannelAccordion, maybe? maybe unnecessary)
- [ ] channel (WithdrawFunds, CloseChannelButton, UpdateState, JoinChannel)

Refactor to show transaction statuses
- [ ] NewChannel Modal (opening new channels)
- [ ] CloseChannel Button
- [ ] JoinChannel Modal
- [ ] UpdateState
- [ ] basically any ethcalate tx calls
